version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: secureapi
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  sync:
    build: ./sync
    depends_on:
      - mysql
      - redis
